"""Constants for tns_energo integration"""
from typing import Final

DOMAIN: Final = "tns_energo"

ATTRIBUTION_EN: Final = "Data acquired from %s"
ATTRIBUTION_RU: Final = "Данные получены с %s"

ATTR_ACCOUNT_CODE: Final = "account_code"
ATTR_ACCOUNT_ID: Final = "account_id"
ATTR_ADDRESS: Final = "address"
ATTR_AMOUNT: Final = "amount"
ATTR_CHECKUP_DATE: Final = "checkup_date"
ATTR_CHECKUP_STATUS: Final = "checkup_status"
ATTR_CHECKUP_URL: Final = "checkup_url"
ATTR_COMMENT: Final = "comment"
ATTR_CONTROLLED_BY_CODE: Final = "controlled_by_code"
ATTR_DIGITAL_INVOICES_EMAIL: Final = "digital_invoices_email"
ATTR_DIGITAL_INVOICES_EMAIL_COMMENT: Final = "digital_invoices_email_comment"
ATTR_DIGITAL_INVOICES_ENABLED: Final = "digital_invoices_enabled"
ATTR_DIGITAL_INVOICES_IGNORED: Final = "digital_invoices_ignored"
ATTR_EMAIL: Final = "email"
ATTR_END: Final = "end"
ATTR_FULL_NAME: Final = "full_name"
ATTR_GROUP: Final = "group"
ATTR_IGNORE_INDICATIONS: Final = "ignore_indications"
ATTR_IGNORE_PERIOD: Final = "ignore_period"
ATTR_INCREMENTAL: Final = "incremental"
ATTR_INDICATIONS: Final = "indications"
ATTR_INITIAL: Final = "initial"
ATTR_INSTALL_DATE: Final = "install_date"
ATTR_INSTALL_LOCATION: Final = "install_location"
ATTR_INSURANCE: Final = "insurance"
ATTR_INVOICE_ID: Final = "invoice_id"
ATTR_IS_CONTROLLED: Final = "is_controlled"
ATTR_IS_CONTROLLING: Final = "is_controlling"
ATTR_LAST_CHECKUP_DATE: Final = "last_checkup_date"
ATTR_LAST_INDICATIONS_DATE: Final = "last_indications_date"
ATTR_LAST_PAYMENT_AMOUNT: Final = "last_payment_amount"
ATTR_LAST_PAYMENT_DATE: Final = "last_payment_date"
ATTR_LAST_PAYMENT_STATUS: Final = "last_payment_status"
ATTR_LIVING_AREA: Final = "living_area"
ATTR_METER_CATEGORY: Final = "meter_category"
ATTR_METER_CODE: Final = "meter_codes"
ATTR_METER_ID: Final = "meter_id"
ATTR_METER_MODEL: Final = "meter_model"
ATTR_MODEL: Final = "model"
ATTR_PAID: Final = "paid"
ATTR_PAID_AT: Final = "paid_at"
ATTR_PENALTY: Final = "penalty"
ATTR_PERIOD: Final = "period"
ATTR_PRECISION: Final = "precision"
ATTR_PREVIOUS: Final = "previous"
ATTR_PROVIDER_NAME: Final = "provider_name"
ATTR_PROVIDER_TYPE: Final = "provider_type"
ATTR_REASON: Final = "reason"
ATTR_RECALCULATIONS: Final = "recalculations"
ATTR_REMAINING_DAYS: Final = "remaining_days"
ATTR_RESULT: Final = "result"
ATTR_SERVICE_NAME: Final = "service_name"
ATTR_SERVICE_TYPE: Final = "service_type"
ATTR_SOURCE: Final = "source"
ATTR_START: Final = "start"
ATTR_STATUS: Final = "status"
ATTR_SUBMIT_PERIOD_ACTIVE: Final = "submit_period_active"
ATTR_SUBMIT_PERIOD_END: Final = "submit_period_end"
ATTR_SUBMIT_PERIOD_START: Final = "submit_period_start"
ATTR_SUCCESS: Final = "success"
ATTR_SUM: Final = "sum"
ATTR_TAKEN_ON: Final = "taken_on"
ATTR_TOTAL: Final = "total"
ATTR_TOTAL_AREA: Final = "total_area"
ATTR_TRANSACTION_ID: Final = "transaction_id"
ATTR_TRANSMISSION_COEFFICIENT: Final = "transmission_coefficient"
ATTR_TYPE: Final = "type"
ATTR_UNIT: Final = "unit"
ATTR_ZONES: Final = "zones"


CONF_ACCOUNTS: Final = "accounts"
CONF_DEV_PRESENTATION: Final = "dev_presentation"
CONF_LAST_INVOICE: Final = "last_invoice"
CONF_LAST_PAYMENT: Final = "last_payment"
CONF_LOGOS: Final = "logos"
CONF_METERS: Final = "meters"
CONF_NAME_FORMAT: Final = "name_format"
CONF_USER_AGENT: Final = "user_agent"

DATA_API_OBJECTS: Final = DOMAIN + "_api_objects"
DATA_ENTITIES: Final = DOMAIN + "_entities"
DATA_FINAL_CONFIG: Final = DOMAIN + "_final_config"
DATA_PROVIDER_LOGOS: Final = DOMAIN + "_provider_logos"
DATA_UPDATE_DELEGATORS: Final = DOMAIN + "_update_delegators"
DATA_UPDATE_LISTENERS: Final = DOMAIN + "_update_listeners"
DATA_YAML_CONFIG: Final = DOMAIN + "_yaml_config"

DEFAULT_NAME_FORMAT_EN_ACCOUNTS: Final = "{account_code} {type_en_cap}"
DEFAULT_NAME_FORMAT_EN_METERS: Final = "{account_code} {type_en_cap} {code}"
DEFAULT_NAME_FORMAT_EN_LAST_INVOICE: Final = "{account_code} {type_en_cap}"
DEFAULT_NAME_FORMAT_EN_LAST_PAYMENT: Final = "{account_code} {type_en_cap}"

DEFAULT_NAME_FORMAT_RU_ACCOUNTS: Final = "{account_code} {type_ru_cap}"
DEFAULT_NAME_FORMAT_RU_METERS: Final = "{account_code} {type_ru_cap} {code}"
DEFAULT_NAME_FORMAT_RU_LAST_INVOICE: Final = "{account_code} {type_ru_cap}"
DEFAULT_NAME_FORMAT_RU_LAST_PAYMENT: Final = "{account_code} {type_ru_cap}"

DEFAULT_MAX_INDICATIONS: Final = 3
DEFAULT_SCAN_INTERVAL: Final = 60 * 60  # 1 hour


SUPPORTED_PLATFORMS: Final = ("sensor",)

FORMAT_VAR_ACCOUNT_CODE: Final = "account_code"
FORMAT_VAR_ACCOUNT_ID: Final = "account_id"
FORMAT_VAR_CODE: Final = "code"
FORMAT_VAR_ID: Final = "id"
FORMAT_VAR_PROVIDER_CODE: Final = "provider_code"
FORMAT_VAR_PROVIDER_NAME: Final = "provider_name"
FORMAT_VAR_TYPE_EN: Final = "type_en"
FORMAT_VAR_TYPE_RU: Final = "type_ru"
